// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/getumen/gogo_crawler/application/usecase"
	"github.com/getumen/gogo_crawler/config"
	"github.com/getumen/gogo_crawler/domains/service_impl"
	"github.com/getumen/gogo_crawler/infras/http"
	"github.com/getumen/gogo_crawler/infras/persistence/mysql"
	redis2 "github.com/getumen/gogo_crawler/infras/persistence/redis"
	"github.com/gomodule/redigo/redis"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitializeCrawler(config2 *config.Config, db *gorm.DB, redisConn *redis.Pool) (usecase.Crawler, error) {
	requestRepository := redis2.NewRequestRedisRepository(redisConn)
	responseRepository := mysql.NewResponseMysqlRepository(db)
	scheduleRule := service_impl.NewPoissonProcessRule()
	scheduleService := service_impl.NewScheduleService(requestRepository, responseRepository, scheduleRule)
	httpClientRepository := http.NewHttpClientRepository(config2)
	downloadService := service_impl.NewDownloadService(httpClientRepository)
	spiderService := service_impl.NewSpiderService()
	itemService := service_impl.NewItemService(responseRepository)
	crawler := usecase.NewCrawler(config2, scheduleService, downloadService, spiderService, itemService)
	return crawler, nil
}
