// Code generated by MockGen. DO NOT EDIT.
// Source: download_service.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	models "github.com/getumen/gogo_crawler/domains/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	sync "sync"
)

// MockDownloadService is a mock of DownloadService interface
type MockDownloadService struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadServiceMockRecorder
}

// MockDownloadServiceMockRecorder is the mock recorder for MockDownloadService
type MockDownloadServiceMockRecorder struct {
	mock *MockDownloadService
}

// NewMockDownloadService creates a new mock instance
func NewMockDownloadService(ctrl *gomock.Controller) *MockDownloadService {
	mock := &MockDownloadService{ctrl: ctrl}
	mock.recorder = &MockDownloadServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDownloadService) EXPECT() *MockDownloadServiceMockRecorder {
	return m.recorder
}

// DoRequest mocks base method
func (m *MockDownloadService) DoRequest(ctx context.Context, in <-chan *models.Request, out chan<- *models.Response, wg *sync.WaitGroup) {
	m.ctrl.Call(m, "DoRequest", ctx, in, out, wg)
}

// DoRequest indicates an expected call of DoRequest
func (mr *MockDownloadServiceMockRecorder) DoRequest(ctx, in, out, wg interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoRequest", reflect.TypeOf((*MockDownloadService)(nil).DoRequest), ctx, in, out, wg)
}
